image: Visual Studio 2019

build:
  verbosity: detailed

artifacts:
  - path: '**\Release\*.nupkg'

build_script:
  - cmd: dotnet build -c Release

test_script:
  - cmd: dotnet test -c Release

deploy:
  - provider: NuGet
    api_key:
      secure: a/4L0oM31gx59E7OAv1kUhzdg33EO3OCitMbgLmyzWXljtbV4vnZNZd+k4RKh8NB
    on:
      appveyor_repo_tag: true
